In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
np

<module 'numpy' from 'C:\\Users\\preci\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [7]:
pd

<module 'pandas' from 'C:\\Users\\preci\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [8]:
plt

<module 'matplotlib.pyplot' from 'C:\\Users\\preci\\Anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py'>

In [9]:
sns

<module 'seaborn' from 'C:\\Users\\preci\\Anaconda3\\lib\\site-packages\\seaborn\\__init__.py'>

In [16]:
a = [1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [17]:
nparr = np.array([1,2,3,4,5])
print(nparr*3)

[ 3  6  9 12 15]


In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
b = np.array([3,6,9])
print(a*b)

[[ 3 12 27]
 [12 30 54]
 [21 48 81]]


In [23]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2],[3,4,5],[6,7,8,9]]) #이런거 안된다는 뜻
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


In [27]:
d = np.zeros((10,3))
print(d)
e = np.zeros(3)
print('-'*20)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------
[0. 0. 0.]


In [28]:
orig = [1,2,3]
print(type(orig))
to_np = np.asarray(orig)
print(type(to_np))
print(to_np)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [29]:
a = np.array([1,2,3])
b = np.array([1,2,3], dtype=np.float64)
print(a)
print(b)

[1 2 3]
[1. 2. 3.]


In [34]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6],[2,4,6]])
print(a+b)
print('-'*20)
print(a-b)
print('-'*20)
print(a*b)
print('-'*20)
print(a/b)
print('-'*20)
print(a**b)
print('-'*20)
print(a%b)
print('-'*20)
print(a>b)
print('-'*20)
print(a==b)

[[ 3  6  9]
 [ 6  9 12]]
--------------------
[[-1 -2 -3]
 [ 2  1  0]]
--------------------
[[ 2  8 18]
 [ 8 20 36]]
--------------------
[[0.5  0.5  0.5 ]
 [2.   1.25 1.  ]]
--------------------
[[    1    16   729]
 [   16   625 46656]]
--------------------
[[1 2 3]
 [0 1 0]]
--------------------
[[False False False]
 [ True  True False]]
--------------------
[[False False False]
 [False False  True]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1]
c = a[:,2]
print(a)
print('-'*20)
print(b)
print('-'*20)
print(c)
c[1] = 3 #원본 값이 바뀝니다
print('-'*20)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[4 5 6]
--------------------
[3 6 9]
--------------------
[[1 2 3]
 [4 5 3]
 [7 8 9]]


In [9]:
a = np.empty((8,4))
for i in range(8):
    a[i] = i
    
print(a)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [12]:
print(a[3])
print('-'*20)
print(a[[4,7,0,3]])

[3. 3. 3. 3.]
--------------------
[[4. 4. 4. 4.]
 [7. 7. 7. 7.]
 [0. 0. 0. 0.]
 [3. 3. 3. 3.]]


In [13]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
b = a.reshape((5,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
c = b.T
c

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [22]:
a = np.array([1,2,5])
b = np.array([2,1,6])
c = np.array([3.3,1.7,2.7])

print(np.maximum(a,b,c))
print(np.minimum(a,b,c))
print(np.divide(a,b,c))
#np.substract: 빼기
#np.multiply: 곱하기
#np.power : 제곱

[2. 2. 6.]
[1. 1. 5.]
[0.5        2.         0.83333333]


In [25]:
d = np.arange(10)
print(d)
np.save('test',d)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
e = np.load('test.npy')
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([3,2,1])
c = a.dot(b)

print(a)
print('-'*20)
print(b)
print('-'*20)
print(c)
print('-'*20)
print(b.T.dot(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[3 2 1]
--------------------
[10 28 46]
--------------------
[18 24 30]


In [39]:
from numpy.linalg import inv, qr, eig, det,svd

In [32]:
eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [33]:
det(a)

-9.51619735392994e-16

In [38]:
b = inv(a)
print(a)
print('-'*20)
print(b)
print('-'*20)
print(a.dot(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
--------------------
[[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]


In [40]:
print(svd(a))

(array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]), array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]]))


In [41]:
print(qr(a))

(array([[-0.12309149,  0.90453403,  0.40824829],
       [-0.49236596,  0.30151134, -0.81649658],
       [-0.86164044, -0.30151134,  0.40824829]]), array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.11164740e-15]]))
