In [1]:
import numpy as np
import pandas as pd

In [28]:
a = pd.Series([3,5,6,8])
a

0    3
1    5
2    6
3    8
dtype: int64

In [27]:
b = pd.DataFrame([[3,5,6,8],[4,8,9,12],[1,5,8,6],[-3,8,123,55]])
b

0  1    2   3
0  3  5    6   8
1  4  8    9  12
2  1  5    8   6
3 -3  8  123  55

In [16]:
c = pd.Series([1,2,3,4], index=['a','b','c','d'])
c

a    1
b    2
c    3
d    4
dtype: int64

In [13]:
d = pd.DataFrame([[3,5,6,8],[4,8,9,12],[1,5,8,6],[-3,8,123,55]], index=['a','b','c','d'])
d

0  1    2   3
a  3  5    6   8
b  4  8    9  12
c  1  5    8   6
d -3  8  123  55

In [79]:
e = pd.DataFrame([[3,5,6,8],[4,8,9,12],[1,5,8,6],[-3,8,123,55]], index=['a','b','c','d'], columns=['A','B','C','D'])
e

A  B    C   D
a  3  5    6   8
b  4  8    9  12
c  1  5    8   6
d -3  8  123  55

In [34]:
f = pd.Series({'A':3,'B':5, 'C':8,'D':15})
f

A     3
B     5
C     8
D    15
dtype: int64

In [35]:
g = pd.DataFrame ( {'V1' : {'A':1,'B':2,'C':3}, 'V2':{'A':5,'B':10,'C':15} })
g

V1  V2
A   1   5
B   2  10
C   3  15

In [56]:
csv = [['순번','이름','점수','성적','기타'], ['0','장태영','50','C+','게으름'],['1','김동현','100','A+','성실함'], ['2','김규원','95','A+','잘생김']]
h = pd.DataFrame(csv[1:])
h.columns = csv[0]
h = h.set_index('순번')
#h.index.names = [None]
h

이름   점수  성적   기타
순번                   
0   장태영   50  C+  게으름
1   김동현  100  A+  성실함
2   김규원   95  A+  잘생김

In [18]:
c['a']

1

In [21]:
e['A']

a    3
b    4
c    1
d   -3
Name: A, dtype: int64

In [23]:
e.loc['a']

A    3
B    5
C    6
D    8
Name: a, dtype: int64

In [80]:
e

A  B    C   D
a  3  5    6   8
b  4  8    9  12
c  1  5    8   6
d -3  8  123  55

In [81]:
e['E'] = [9,8,27,36]
e

A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  1  5    8   6  27
d -3  8  123  55  36

In [82]:
e.loc['e'] = [7,8,9,10,11]
e

A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  1  5    8   6  27
d -3  8  123  55  36
e  7  8    9  10  11

In [30]:
a[a>5]

2    6
3    8
dtype: int64

In [66]:
e[e>5]

A    B    C   D   E
a  NaN  NaN    6   8   9
b  NaN  8.0    9  12   8
c  NaN  NaN    8   6  27
d  NaN  8.0  123  55  36
e  7.0  8.0    9  10  11

In [67]:
e[e>5].isnull()

A      B      C      D      E
a   True   True  False  False  False
b   True  False  False  False  False
c   True   True  False  False  False
d   True  False  False  False  False
e  False  False  False  False  False

In [77]:
e.T

a   b   c    d   e
A  3   4   1   -3   7
B  5   8   5    8   8
C  6   9   8  123   9
D  8  12   6   55  10
E  9   8  27   36  11

In [90]:
i = pd.Series([1,2,3,4], index=['a','b','c','d'])
i

a    1
b    2
c    3
d    4
dtype: int64

In [92]:
i2 = i.reindex(['d','a','b','c'])
i2

d    4
a    1
b    2
c    3
dtype: int64

In [96]:
i3 = i.reindex(['F','G','H','I']) #없는 인덱스에 이름 새로 지어주겠다고 하면 안됨
print(i3)
print('-'*20)
print(i.index)

F   NaN
G   NaN
H   NaN
I   NaN
dtype: float64
--------------------
Index(['a', 'b', 'c', 'd'], dtype='object')


In [101]:
i.index = ['F','G','H','I']
i

F    1
G    2
H    3
I    4
dtype: int64

In [107]:
g = e
e

A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  1  5    8   6  27
d -3  8  123  55  36
e  7  8    9  10  11

In [106]:
g['A'][2]

1

In [108]:
g['A'][2] = 5

In [109]:
e

A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  5  5    8   6  27
d -3  8  123  55  36
e  7  8    9  10  11

In [112]:
k = e.copy()
k
k['A'][2] = 1
print(e)
print('-'*20)
print(k)

   A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  5  5    8   6  27
d -3  8  123  55  36
e  7  8    9  10  11
--------------------
   A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
c  1  5    8   6  27
d -3  8  123  55  36
e  7  8    9  10  11


In [116]:
k.drop('c')

A  B    C   D   E
a  3  5    6   8   9
b  4  8    9  12   8
d -3  8  123  55  36
e  7  8    9  10  11

In [119]:
k.drop('D', axis=1)

A  B    C   E
a  3  5    6   9
b  4  8    9   8
c  1  5    8  27
d -3  8  123  36
e  7  8    9  11

In [123]:
l = k['b':'d']
l

A  B    C   D   E
b  4  8    9  12   8
c  1  5    8   6  27
d -3  8  123  55  36

In [126]:
m = k[:'a'] 
n = k['d':]

In [128]:
o = m.append(n)
o

A  B    C   D   E
a  3  5    6   8   9
d -3  8  123  55  36
e  7  8    9  10  11

In [131]:
m1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
m2 = pd.DataFrame([[1,3,5],[7,9,7],[5,3,1]])
print('add')
print(m1+m2)
print('-'*20)
print('susbstract')
print(m1-m2)
print('-'*20)
print('div')
print(m1/m2)
print('-'*20)
print('floordiv')
print(m1//m2)
print('multiply')
print('-'*20)
print('modular')
print(m1%m2)
print('-'*20)
print('power')
print(m1**m2)
print('-'*20)
print('condition, return Boolean')
print(m1>m2)
print('-'*20)

add
    0   1   2
0   2   5   8
1  11  14  13
2  12  11  10
--------------------
susbstract
   0  1  2
0  0 -1 -2
1 -3 -4 -1
2  2  5  8
--------------------
div
          0         1         2
0  1.000000  0.666667  0.600000
1  0.571429  0.555556  0.857143
2  1.400000  2.666667  9.000000
--------------------
floordiv
   0  1  2
0  1  0  0
1  0  0  0
2  1  2  9
multiply
--------------------
modular
   0  1  2
0  0  2  3
1  4  5  6
2  2  2  0
--------------------
power
       0        1       2
0      1        8     243
1  16384  1953125  279936
2  16807      512       9
--------------------
condition, return Boolean
       0      1      2
0  False  False  False
1  False  False  False
2   True   True   True
--------------------


In [161]:
m1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
s1 = pd.Series([3,6,9])
print('add')
print(m1+s1)
print('-'*20)
print('susbstract')
print(m1-s1)
print('-'*20)
print('div')
print(m1/s1)
print('-'*20)
print('floordiv')
print(m1//s1)
print('multiply')
print('-'*20)
print('modular')
print(m1%s1)
print('-'*20)
print('power')
print(m1**s1)
print('-'*20)
print('condition, return Boolean')
print(m1>s1)
print('-'*20)

add
    0   1   2
0   4   8  12
1   7  11  15
2  10  14  18
3  13  17  21
--------------------
susbstract
   0  1  2
0 -2 -4 -6
1  1 -1 -3
2  4  2  0
3  7  5  3
--------------------
div
          0         1         2
0  0.333333  0.333333  0.333333
1  1.333333  0.833333  0.666667
2  2.333333  1.333333  1.000000
3  3.333333  1.833333  1.333333
--------------------
floordiv
   0  1  2
0  0  0  0
1  1  0  0
2  2  1  1
3  3  1  1
multiply
--------------------
modular
   0  1  2
0  1  2  3
1  1  5  6
2  1  2  0
3  1  5  3
--------------------
power
      0        1           2
0     1       64       19683
1    64    15625    10077696
2   343   262144   387420489
3  1000  1771561  5159780352
--------------------
condition, return Boolean
       0      1      2
0  False  False  False
1   True  False  False
2   True   True  False
3   True   True   True
--------------------


In [153]:
nd = m1.to_numpy()
nd

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [154]:
nd.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [155]:
nd.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [156]:
m2 = pd.DataFrame(nd.reshape(3,4))
m2

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [164]:
m1

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [162]:
m1.sum()

0    22
1    26
2    30
dtype: int64

In [163]:
m1.sum(axis='columns')

0     6
1    15
2    24
3    33
dtype: int64

In [165]:
m1.cumsum()

0   1   2
0   1   2   3
1   5   7   9
2  12  15  18
3  22  26  30

In [166]:
m1.describe()

0          1          2
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000